#!/usr/bin/env ruby
# Comments on a card as the signed-in user.
#
#   planka comment <card> <text>     the card as an id or card URL
#
# Runs as the user configured in PLANKA_AGENT_EMAIL.
require "planka"
require "planka/cli"
require "planka/client"

options = {}
parser = Planka::CLI.output_parser(options, "usage: planka comment <card> <text> [--output human|json]")
parser.separator "Use planka create comment --card CARD --text TEXT for data/meta/error results."
Planka::CLI.parse!(parser, "planka comment")
abort parser.banner unless ARGV.size == 2

begin
  card_id = Planka.card_id(ARGV.first)

  Planka::Client.session do |client|
    comment = client.comment(card_id, ARGV.last).fetch("item")
    result = { "cardId" => card_id, "comment" => comment.slice("id", "text", "userId", "createdAt") }
    Planka::CLI.emit(result, output: options[:output], human: "Commented on card #{card_id}")
  end
rescue Planka::Error, KeyError => e
  abort "planka comment: #{e.message}"
end
