#!/usr/bin/env ruby
# Renames a task list by its id, keeping its tasks. Renaming takes an id, never a
# name, so it can never change the wrong list.
#
#   planka rename-task-list --id TASK_LIST_ID --name NAME
require "planka"
require "planka/cli"
require "planka/client"
require "optparse"

options = {}
parser = OptionParser.new do |o|
  o.banner = "usage: planka rename-task-list --id TASK_LIST_ID --name NAME [--output human|json]"
  o.on("--id ID", "task list id") { |v| options[:id] = v }
  o.on("--name NAME", "new name") { |v| options[:name] = v }
  o.separator "Canonical replacement: planka update task-list TASK_LIST --name NAME (new JSON envelope)."
  Planka::CLI.output_option(o, options)
end
Planka::CLI.parse!(parser, "planka rename-task-list")

Planka::CLI.run("planka rename-task-list", output: options[:output]) do |client|
  id = options.fetch(:id) { raise Planka::Error, "--id is required" }
  name = options.fetch(:name) { raise Planka::Error, "--name is required" }
  result = Planka::TaskLists.new(client).rename(task_list_id: id, name:)
  Planka::CLI.emit(result, output: options[:output], human: Planka::CLI.resource_result("Renamed", "task list", result["taskList"]))
end
