#!/usr/bin/env ruby
# Prints the branch a card is worked on, e.g.
# feature/tracer-1.2-an-account-signs-in-the-first-admin. Read-only.
#
#   planka-branch-name <card>     an id or card URL
#
# The logic lives in lib/planka/branch_name.rb.
require "planka"
require "planka/client"

options = {}
parser = Planka::CLI.output_parser(options, "usage: planka branch-name <card> [--output human|json]")
Planka::CLI.parse!(parser, "planka-branch-name")
abort parser.banner unless ARGV.size == 1

begin
  card_id = Planka.card_id(ARGV.first)

  Planka::Client.session do |client|
    board = Planka::Board.new(client.board(client.card(card_id).dig("item", "boardId")))
    branch = Planka::BranchName.for(board.card(card_id))
    Planka::CLI.emit({ "cardId" => card_id, "branch" => branch }, output: options[:output], human: branch)
  end
rescue Planka::Error, KeyError => e
  abort "planka-branch-name: #{e.message}"
end
